name: dj_mania
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_phoenix: ^1.0.0
  blur: ^2.0.0
  flutter_bloc: ^7.0.0

  animation_wrappers: ^0.0.4
  google_maps_flutter: ^2.2.1
  flutter_polyline_points: ^1.0.0
  sign_in_with_apple: ^3.3.0
  google_sign_in: ^5.1.1-nullsafety
  equatable: ^2.0.3
  shared_preferences: ^2.0.13
  crypto: ^3.0.1
  string_similarity: ^2.0.0
  table_calendar: ^3.0.6
  #flutter_facebook_auth: ^3.3.3-nullsafety.2
  #flutter_facebook_auth: ^4.4.0
  another_flushbar: ^1.10.28
  flutter_redux: ^0.10.0
  intl: ^0.17.0
  image_picker: ^0.8.0

  #image_picker: ^0.8.6
  http_parser: ^4.0.1

  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  fl_chart: ^0.36.1
  provider: ^5.0.0
  circular_chart_flutter: ^0.0.2
  chart_sparkline: ^1.0.11
  cached_network_image: ^3.2.0
  badges: ^2.0.3
  flutter_app_lock: ^1.4.0+1
  container_tab_indicator: ^0.3.0
  dots_indicator: ^2.1.0
  sizer: ^2.0.15
  flutter_statusbarcolor_ns: ^0.4.0
  #flutter_html: ^2.0.0
  flutter_inappwebview_quill: ^5.4.6
  scroll_indicator: ^0.0.3
  page_view_indicators: ^2.0.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  #permission_handler: ^10.2.0

  #flutter_inappwebview: ^5.4.3+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"

flutter_launcher_name:
  name: "Joinn"

flutter:
  uses-material-design: true

  fonts:
    - family: harmonia
      fonts:
        - asset: fonts/hregular.ttf
        - asset: fonts/hbold.ttf
          weight: 700

        - asset: fonts/hlight.ttf
        - asset: fonts/hlight.ttf
          style: normal

  assets:
    - assets/
    - assets/icons/
    - assets/event/
    - assets/avatars/
    - assets/dj/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
